export interface Brand {
  id: string
  name: string
  reach: string
  cpm: string
  logo: string
  category: "Digital" | "CTV" | "DOOH" | "App" | "Smart Devices"
  targetGroup: string[]
  tags: string[]
  impressions: string
  description: string
}

export const allBrands: Brand[] = [
  // Digital Brands
  {
    id: "digital-1",
    name: "Google Ads",
    reach: "800M",
    cpm: "₹120",
    logo: "/placeholder.svg?height=24&width=24&text=GA",
    category: "Digital",
    targetGroup: ["SMBs", "Tech Enthusiasts"],
    tags: ["Tier-1", "Performance-First"],
    impressions: "2.5M",
    description: "Reach your audience across Google's vast network with targeted advertising solutions.",
  },
  {
    id: "digital-2",
    name: "Meta",
    reach: "2.5B",
    cpm: "₹180",
    logo: "/placeholder.svg?height=24&width=24&text=M",
    category: "Digital",
    targetGroup: ["GenZ", "Millennials"],
    tags: ["Tier-1", "Social", "Youth"],
    impressions: "5.2M",
    description: "Connect with billions of users across Facebook, Instagram, and WhatsApp platforms.",
  },
  {
    id: "digital-3",
    name: "TikTok",
    reach: "1B",
    cpm: "₹210",
    logo: "/placeholder.svg?height=24&width=24&text=TT",
    category: "Digital",
    targetGroup: ["GenZ", "Youth"],
    tags: ["Video", "Influencer"],
    impressions: "3.8M",
    description: "Engage with the next generation through creative short-form video content.",
  },
  {
    id: "digital-4",
    name: "LinkedIn",
    reach: "300M",
    cpm: "₹290",
    logo: "/placeholder.svg?height=24&width=24&text=LI",
    category: "Digital",
    targetGroup: ["Professionals", "B2B"],
    tags: ["B2B", "Professional"],
    impressions: "1.2M",
    description: "Target professionals and decision-makers in the world's largest professional network.",
  },
  {
    id: "digital-5",
    name: "Pinterest",
    reach: "400M",
    cpm: "₹150",
    logo: "/placeholder.svg?height=24&width=24&text=P",
    category: "Digital",
    targetGroup: ["Lifestyle", "Home Decor"],
    tags: ["Visual", "Inspiration"],
    impressions: "1.8M",
    description: "Inspire and reach users through visual discovery and lifestyle content.",
  },
  // CTV Brands
  {
    id: "ctv-1",
    name: "Hotstar",
    reach: "300M",
    cpm: "₹450",
    logo: "/placeholder.svg?height=24&width=24&text=HS",
    category: "CTV",
    targetGroup: ["Sports Fans", "Family Audience"],
    tags: ["Streaming", "Entertainment"],
    impressions: "4.5M",
    description: "Reach millions of viewers through premium sports and entertainment content.",
  },
  {
    id: "ctv-2",
    name: "SonyLIV",
    reach: "150M",
    cpm: "₹380",
    logo: "/placeholder.svg?height=24&width=24&text=SL",
    category: "CTV",
    targetGroup: ["Youth", "Drama Lovers"],
    tags: ["Streaming", "Regional"],
    impressions: "2.8M",
    description: "Connect with audiences through diverse regional and international content.",
  },
  {
    id: "ctv-3",
    name: "Zee5",
    reach: "100M",
    cpm: "₹320",
    logo: "/placeholder.svg?height=24&width=24&text=Z5",
    category: "CTV",
    targetGroup: ["General Audience"],
    tags: ["Streaming", "Bollywood"],
    impressions: "2.1M",
    description: "Engage with diverse audiences through Bollywood and regional entertainment.",
  },
  {
    id: "ctv-4",
    name: "Amazon Prime",
    reach: "80M",
    cpm: "₹580",
    logo: "/placeholder.svg?height=24&width=24&text=AP",
    category: "CTV",
    targetGroup: ["Premium Audience"],
    tags: ["Tier-1", "Exclusive Content"],
    impressions: "1.9M",
    description: "Target premium audiences with exclusive content and original series.",
  },
  {
    id: "ctv-5",
    name: "Netflix",
    reach: "40M",
    cpm: "₹620",
    logo: "/placeholder.svg?height=24&width=24&text=N",
    category: "CTV",
    targetGroup: ["Premium Audience"],
    tags: ["Tier-1", "Global Content"],
    impressions: "1.5M",
    description: "Reach global audiences through premium original content and series.",
  },
  // DOOH Brands
  {
    id: "dooh-1",
    name: "Times OOH",
    reach: "50M",
    cpm: "₹280",
    logo: "/placeholder.svg?height=24&width=24&text=TO",
    category: "DOOH",
    targetGroup: ["Urban Commuters"],
    tags: ["Outdoor", "High Footfall"],
    impressions: "3.2M",
    description: "Capture attention in high-traffic urban locations and transit hubs.",
  },
  {
    id: "dooh-2",
    name: "JCDecaux",
    reach: "40M",
    cpm: "₹300",
    logo: "/placeholder.svg?height=24&width=24&text=JC",
    category: "DOOH",
    targetGroup: ["Mass Market"],
    tags: ["Outdoor", "Transit"],
    impressions: "2.8M",
    description: "Reach mass audiences through strategic outdoor and transit advertising.",
  },
  {
    id: "dooh-3",
    name: "Selvel One",
    reach: "25M",
    cpm: "₹250",
    logo: "/placeholder.svg?height=24&width=24&text=SO",
    category: "DOOH",
    targetGroup: ["Local Audience"],
    tags: ["Outdoor", "Local"],
    impressions: "1.8M",
    description: "Connect with local communities through targeted outdoor advertising.",
  },
  {
    id: "dooh-4",
    name: "Laqshya Media",
    reach: "30M",
    cpm: "₹310",
    logo: "/placeholder.svg?height=24&width=24&text=LM",
    category: "DOOH",
    targetGroup: ["Urban Commuters"],
    tags: ["Outdoor", "Premium Locations"],
    impressions: "2.2M",
    description: "Premium outdoor advertising in high-visibility urban locations.",
  },
  {
    id: "dooh-5",
    name: "Moving Walls",
    reach: "35M",
    cpm: "₹290",
    logo: "/placeholder.svg?height=24&width=24&text=MW",
    category: "DOOH",
    targetGroup: ["Mass Market"],
    tags: ["Outdoor", "Digital Screens"],
    impressions: "2.5M",
    description: "Dynamic digital outdoor advertising with real-time content updates.",
  },
  // App Brands
  {
    id: "app-1",
    name: "Rapido",
    reach: "20M",
    cpm: "₹150",
    logo: "/placeholder.svg?height=24&width=24&text=R",
    category: "App",
    targetGroup: ["Commuters", "Youth"],
    tags: ["In-App", "Mobility"],
    impressions: "1.5M",
    description: "Reach daily commuters through India's leading bike taxi platform.",
  },
  {
    id: "app-2",
    name: "Swiggy",
    reach: "50M",
    cpm: "₹200",
    logo: "/placeholder.svg?height=24&width=24&text=S",
    category: "App",
    targetGroup: ["Foodies", "Urban Dwellers"],
    tags: ["In-App", "Food Delivery"],
    impressions: "3.5M",
    description: "Connect with food lovers through India's largest food delivery platform.",
  },
  {
    id: "app-3",
    name: "Zomato",
    reach: "45M",
    cpm: "₹190",
    logo: "/placeholder.svg?height=24&width=24&text=Z",
    category: "App",
    targetGroup: ["Foodies", "Restaurant Goers"],
    tags: ["In-App", "Food Discovery"],
    impressions: "3.2M",
    description: "Engage with food enthusiasts and restaurant discovery audiences.",
  },
  {
    id: "app-4",
    name: "Ola",
    reach: "35M",
    cpm: "₹170",
    logo: "/placeholder.svg?height=24&width=24&text=O",
    category: "App",
    targetGroup: ["Urban Commuters", "Travelers"],
    tags: ["In-App", "Transportation"],
    impressions: "2.8M",
    description: "Reach urban commuters through comprehensive mobility solutions.",
  },
  // Smart Devices (AI Kiosk) Brands
  {
    id: "smart-1",
    name: "IntelliKiosk Pro",
    reach: "15M",
    cpm: "₹350",
    logo: "/placeholder.svg?height=24&width=24&text=IK",
    category: "Smart Devices",
    targetGroup: ["Tech Enthusiasts", "Retail Shoppers"],
    tags: ["AI", "Interactive", "Retail"],
    impressions: "1.2M",
    description: "Interactive AI-powered kiosks for enhanced retail customer engagement.",
  },
  {
    id: "smart-2",
    name: "SmartDisplay Network",
    reach: "12M",
    cpm: "₹320",
    logo: "/placeholder.svg?height=24&width=24&text=SD",
    category: "Smart Devices",
    targetGroup: ["Mall Visitors", "Urban Audience"],
    tags: ["AI", "Touch Screen", "Mall"],
    impressions: "980K",
    description: "Smart interactive displays in premium shopping and entertainment venues.",
  },
  {
    id: "smart-3",
    name: "AI Concierge Systems",
    reach: "8M",
    cpm: "₹400",
    logo: "/placeholder.svg?height=24&width=24&text=AC",
    category: "Smart Devices",
    targetGroup: ["Hotel Guests", "Business Travelers"],
    tags: ["AI", "Hospitality", "Premium"],
    impressions: "650K",
    description: "AI-powered concierge systems for premium hospitality experiences.",
  },
  {
    id: "smart-4",
    name: "Interactive Wayfinding",
    reach: "10M",
    cpm: "₹280",
    logo: "/placeholder.svg?height=24&width=24&text=IW",
    category: "Smart Devices",
    targetGroup: ["Airport Travelers", "Hospital Visitors"],
    tags: ["AI", "Navigation", "Public Spaces"],
    impressions: "820K",
    description: "Smart wayfinding solutions for airports, hospitals, and public spaces.",
  },
  {
    id: "smart-5",
    name: "Smart Retail Kiosks",
    reach: "18M",
    cpm: "₹380",
    logo: "/placeholder.svg?height=24&width=24&text=SR",
    category: "Smart Devices",
    targetGroup: ["Shoppers", "Tech-Savvy Consumers"],
    tags: ["AI", "E-commerce", "Self-Service"],
    impressions: "1.4M",
    description: "Self-service retail kiosks with AI-powered product recommendations.",
  },
]
